EPSI/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'ipaddr', to: 'home#show'
  get 'pword', to: 'home#pass'
  post 'filename' , to: 'home#upload'
  get 'iface', to: 'home#sniff'

  resources :pages do
	collection do
		get :scan
	end
  end


end

EPSI/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include PacketFu
end

EPSI/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  extend PacketFu
end

EPSI/app/controllers/home_controller.rb
class HomeController < ApplicationController
	include PacketFu
	extend PacketFu

   def index
     # don't need to do anything here (too simple of an application). Usually will do work here.
   end

   def show
		@ipaddress = params[:ipaddr]

		require 'nmap/program'
		Nmap::Program.sudo_scan do |nmap|
			nmap.syn_scan = false
			nmap.service_scan = false
			nmap.os_fingerprint = false
			nmap.xml = 'scan.xml'
			nmap.verbose = true
			nmap.ports = [22, 80]
			nmap.targets = @ipaddress
		end
	end

	def pass
		load "#{Rails.root}/lib/words4.rb"
		load "#{Rails.root}/lib/words5.rb"
		load "#{Rails.root}/lib/specials.rb"
		load "#{Rails.root}/lib/numbers.rb"
		load "#{Rails.root}/lib/words4up.rb"
		load "#{Rails.root}/lib/words5up.rb"

		@pw = params[:pword]

		@c0 = params[:c0]
		@c1 = params[:c1]
		@c2 = params[:c2]
		
		#for each constraint
		if(!@c0 && !@c1 && !@c2)
			@password = dictionary4.sample + @pw
		end

		if(@c0 && !@c1 && !@c2)
			@password = dictionary4up.sample + @pw
		end
		if(!@c0 && @c1 && !@c2)
			@password = dictionary4.sample + @pw + dictionaryN.sample
		end
		if(!@c0 && !@c1 && @c2)
			@password = dictionary4.sample + dictionaryS.sample + @pw
		end

		if(@c0 && @c1 && !@c2)
			@password = dictionary4up.sample + @pw + dictionaryN.sample
		end
		if(!@c0 && @c1 && @c2)
			@password = dictionary4.sample + dictionaryS.sample + @pw + dictionaryN.sample
		end
		if(@c0 && !@c1 && @c2)
			@password = dictionary4up.sample + dictionaryS.sample + @pw
		end

		if(@c0 && @c1 && @c2)
			@password = dictionary4up.sample + dictionaryS.sample + @pw + dictionaryN.sample
		end

	end

	def upload
		require 'packetfu'
		require 'chartkick'
		@fn = params[:filename]
		@filename = @fn.original_filename
		File.open(Rails.root.join('public', @fn.original_filename), 'wb') do |file|
        file.write(@fn.read)
    	end
	end


	def sniff
	  require 'rubygems'
	  require 'packetfu'

	  @iface = params[:iface]

	end


end

EPSI/app/helpers/application_helper.rb
module ApplicationHelper
end

EPSI/app/views/home/file.html.erb
<% require 'packetfu' %>

<% @packet_array.each do |pkt| %>
	<% @packet = PacketFu::Packet.parse(pkt) %>
	<% if(@packet.class != InvalidPacket) %>
		<% if @packet.is_ip? %>
			<% @packet_info = [@packet.ip_saddr, @packet.ip_daddr, @packet.size, @packet.proto.last] %>
			<%= print num %>
			<%= puts ". %-15s -> %-15s %-4d %s" % @packet_info %>
			<% num = num + 1 %>
		<% else %>
			<% @packet_info = [@packet.eth_saddr, @packet.eth_daddr, @packet.size, @packet.proto.last] %>
			<%= print num %>
			<%= puts ". %-15s -> %-15s %-4d %s" % @packet_info %>
			<% num = num + 1 %>
		<% end %>
	<% else %>
		<%= print num %>
		<% sniff = @packet.peek %>
		<% @packet_info = [sniff[20..21], sniff[22..23], sniff[24..25], sniff[26..27], sniff[28..29], sniff[30..31], sniff[8..9], sniff[10..11], sniff[12..13], sniff[14..15], sniff[16..17], sniff[18..19], @packet.size, sniff[0]] %>
		<%= puts ". %-2s:%-2s:%-2s:%-2s:%-2s:%-2s -> %-2s:%-2s:%-2s:%-2s:%-2s:%-2s %-4d %s" % @packet_info %>
		<% num = num + 1 %>
	<% end %>

<% end %>

EPSI/app/views/home/index.html.erb
<html>
<style>
table {
	border-collapse: separate;
}

h3 {
	font-family: "Comic Sans MS", cursive, sans-serif;
		text-shadow: 1px 1px #999;	

}

#boxes {
  font-family: "Comic Sans MS", cursive, sans-serif;
  color: #001111;
  font-size: 80%;
}

.button{
  color: #001111;
  width: 80%;
  height: 30px;
  border: 1px solid;
  border-radius: 7px;
  background-color: #32cd32;
  color: #FFFFFF;


}

#cboxes {
  font-family: "Comic Sans MS", cursive, sans-serif;
  color: #001111;
  font-size: 60%;
}

td {
	margin: 10px 10px 10px 10px;
}

#texts {
	font-family: "Comic Sans MS", cursive, sans-serif;
	text-shadow: 1px 1px #999;	
	color: #32cd32;
}

#rcorners2 {
	box-shadow: 5px 5px 5px #999;
    text-align: center;
	font-family: "Comic Sans MS", cursive, sans-serif;
    border-radius: 25px;
    border: 3px solid #32cd32;
    padding: 20px; 
    width: 200px;
    height: 150px; 
    display: inline-block;
}

#spacer {
	padding: 10px 100px 200px 200px;
	display: inline-block;
}
</style>

<center>
<div id ="texts"> <h1> Easy-Passive-Security-Interface <h1> </div>

<% default = "10.0.0.*" %>
<table><tr> 
<td id="rcorners2" ><h3>Scan</h3> 
<div id="boxes" align="center">
<%= form_tag(ipaddr_path, method: "get") do %>
	<%= label_tag(:ipaddr, "Enter address range") %>
	<%= text_field_tag(:ipaddr, "ex: #{default}") %>
	<br><br><br>
	<%= submit_tag("Find Devices", :class => "button") %>
	<% end %>
</div></td>

<td id="rcorners2"><h3>Analyze</h3> 
<div id="boxes" align="center">
<%= form_tag({action: :upload}, multipart: true) do %>
	<%= label_tag(:upload, "Upload a file .pcap") %>
	<%= file_field_tag 'filename' %>
	<br><br><br>
	<%= submit_tag("Upload .pcap", :class => "button") %>
	<% end %>
</div></td> 

<td id="rcorners2"><h3>Capture</h3>
<div id="boxes" align="center">
<%= form_tag(iface_path, method: "get") do %>
	<%= label_tag(:iface, "Enter a network interface") %>
	<%= text_field_tag(:iface_path, "ex: wlan1") %>
	<br><br><br>
	<%= submit_tag("Sniff Network", :class => "button") %>
	<% end %>
 </div></td>

<td id="rcorners2"><h3>Improve</h3>
<div id="boxes" align="center">
<%= form_tag(pword_path, method: "get") do %>
	<%= label_tag(:pword, "Enter your old password") %>
	<%= text_field_tag(:pword) %>
	<div id="cboxes">
	<%= check_box_tag 'c0', 1, true  %>
	<%= label_tag 'Upper Case' %>
	<%= check_box_tag 'c1', 1, true  %>
	<%= label_tag 'Digits' %>
	<%= check_box_tag 'c2', 1, true %>
	<%= label_tag 'Special' %>
	</div>
	<br>
	<%= submit_tag("Generate Password", :class => "button") %>
	<% end %>
</div></td> 

</tr></table>
</center>

</html>

EPSI/app/views/home/pass.html.erb
<html>

<style>

body {
  padding: 20px;
  font-family: sans-serif;
}

#texts {
	font-family: "Comic Sans MS", cursive, sans-serif;
	text-shadow: 1px 1px #999;	
	color: #32cd32;
}

#boxes {
  font-family: "Comic Sans MS", cursive, sans-serif;
  color: #000000;
  font-size: 60%;
}

#rcorners2 {
    border-radius: 25px;
    border: 3px solid #32cd32;
    padding: 20px; 
    width: 200px;
    display: inline-block;
    vertical-align: center;
    box-shadow: 5px 5px 5px #999;
}

#spacer {
  padding: 10px 10px 10px 10px;
  display: inline-block;
  vertical-align: center;

}
</style>

<center>
<div id="texts" align="center">
<h1> Perfect your password </h1>
</div>
<div id="texts" align="center">
<%= form_tag(pword_path, method: "get") do %>
  <%= label_tag(:pword, "Enter your old password ") %>
  <%= text_field_tag(:pword) %>
  <%= submit_tag("Improve it!") %>
  <br>

  <div id="boxes">
  <%= check_box_tag 'c0', 1, true  %>
  <%= label_tag 'Upper Case' %>
  <%= check_box_tag 'c1', 1, true  %>
  <%= label_tag 'Digits' %>
  <%= check_box_tag 'c2', 1, true %>
  <%= label_tag 'Special Char' %>
  <%#= check_box_tag 'c3', 1, true %>
  <%#= label_tag 'No Spaces' %>
  <%#= check_box_tag 'c4', 1, true  %>
  <%#= label_tag 'Length 8' %>
  </div>

  <% end %>
</div>

<div id="texts" align="center">
<h1> New password </h1>
</div>
<div id="rcorners2">
<div id="spacer">
<table id="rcorners">
  <td><%= "#{@password}" %></td>
</table>
</div>
</div>


<div id="texts" align="center">
<h1> Not satisfied? Try again </h1>
</div>
</center>

EPSI/app/views/home/show.html.erb
<html>
<style>
table {
   box-shadow: 5px 5px 5px #999;
   font-family: "Comic Sans MS", cursive, sans-serif;
   text-align: center;
}

#texts {
	font-family: "Comic Sans MS", cursive, sans-serif;
	text-align: left;
	text-shadow: 1px 1px #999;	
	color: #32cd32;
}

#rcorners2 {
    border-radius: 25px;
    border: 3px solid #32cd32;
    padding: 20px; 
    width: 200px;
    height: 150px; 
    display: inline-block;
}

#spacer {
	padding: 10px;
	display: inline-block;
}
</style>

<%= `date` %>
<br>

	
<% require 'nmap/xml' %>
<% require 'mac_vendor' %>

<div id="texts">
<h1 align="center"><%= "Connected devices on #{@ipaddress}" %></h1>
</div>
<center>
<% Nmap::XML.new('scan.xml') do |xml| %>
	<% xml.each_host do |host| %>
    	<% if host.ports.empty? == false && host.mac.nil? == false %>
    		<div id="spacer">
    		<table id="rcorners2"> 
			<tr><td> <%= host.ip %> </td></tr>
			<tr><td> MAC:<%= host.mac %> </td></tr>
			<% if host.mac.nil? == false %>
				<% name = %x[curl https://mac-to-vendor.herokuapp.com/#{host.mac}] %>
			<tr><td><%= name %></td></tr>
			</table>
			</div>
			<% end %>
		<% end %>
 	<%end%>
<%end%>
</center>

<div id="texts">
<h1 align="center"> Scan another local subnet </h1>
</div>

<div id="texts">
<div align="center">
<%= form_tag(ipaddr_path, method: "get") do %>
	<%= label_tag(:ipaddr, "Enter Address Range (10.0.0.*) ") %>
	<%= text_field_tag(:ipaddr) %>
	<%= submit_tag("Scan") %>
	<% end %>
</div>
</div>

EPSI/app/views/home/sniff.html.erb
 <% num = 0 %>
  <% cap = Capture.new(:iface => "wlan1", :start => true, :promisc => true) %>
  
 <% cap.stream.each do |p| %>
  <% pkt = Packet.parse p %>
  <% if(pkt.class != InvalidPacket) %>
    <% if pkt.is_ip? %>
   	  <% packet_info = [pkt.ip_saddr, pkt.ip_daddr, pkt.size, pkt.proto.last] %>
      <%= num %>
      <%= ". %-17s -> %-15s %-4d %s" % packet_info %>
      <% print num %>
      <% puts  ". %-17s -> %-15s %-4d %s" % packet_info %>
      <% num = num + 1 %> 
      <br>
     <% else %>
       <% packet_info = [pkt.eth_saddr, pkt.eth_daddr, pkt.size, pkt.proto.last] %>
       <%= num %>
       <%= ". %-15s -> %-15s %-4d %s" % packet_info %>
       <% print num %>
       <% puts ". %-15s -> %-15s %-4d %s" % packet_info %>
       <% num = num + 1 %>
       <br>
     <% end %>
   <% else %>
     <%= num %>
     <% sniff = pkt.peek %>
     <% packet_info = [sniff[20..21], sniff[22..23], sniff[24..25], sniff[26..27], sniff[28..29], sniff[30..31], sniff[8..9], sniff[10..11], sniff[12..13], sniff[14..15], sniff[16..17], sniff[18..19], pkt.size, sniff[0]] %>
     <%= ". %-2s:%-2s:%-2s:%-2s:%-2s:%-2s -> %-2s:%-2s:%-2s:%-2s:%-2s:%-2s %-4d %s !!!!!" % packet_info %>
     <% num = num + 1 %>
     <br>
   <% end %>


 <% end %>

EPSI/app/views/home/upload.html.erb
<style>


#texts {
	font-family: "Comic Sans MS", cursive, sans-serif;
	text-shadow: 1px 1px #999;	
	color: #32cd32;
}

#boxes {
  font-family: "Comic Sans MS", cursive, sans-serif;
  color: #000000;
  font-size: 60%;
}

#rcorners2 {
    border-radius: 25px;
    border: 3px solid #32cd32;
    padding: 20px; 
    box-shadow: 5px 5px 5px #999;
}

#spacer {
  padding: 10px 10px 10px 10px;
  display: inline-block;
  vertical-align: center;

}
</style>

<% path = Rails.root.join('public', "#{@filename}") %>
<% @packet_array = PacketFu::PcapFile.file_to_array(path) %>

<% hosts = Array.new %>
<% usage = Array.new %>
<% types = Array.new %>
<% counts = Array.new %>
<% unknwn = 0 %>
<% total = 0 %>


<% @packet_array.each do |pkt| %>
	<% total = total + 1 %>
	<% @packet = PacketFu::Packet.parse(pkt) %>
	<% if(@packet.class != InvalidPacket) %>
		<% if types.include?(@packet.proto.last) %>
			<% type_index = types.index(@packet.proto.last) %>
			<% counts[type_index] = counts[type_index] + 1 %>
		<% else %>
			<% types.push(@packet.proto.last) %>
			<% counts.push(1) %>
		<% end %>
		<% if @packet.is_ip? %>
			<% if hosts.include?(@packet.eth_daddr) %>
				<% host_index = hosts.index(@packet.eth_daddr) %>
				<% usage[host_index] = usage[host_index].to_i + @packet.size.to_i %>
			<% else %>
				<% hosts.push(@packet.eth_daddr) %>
				<% sum = @packet.size.to_i %>
				<% usage.push(sum) %>
			<% end %>
		<% else %>
			<% if hosts.include?(@packet.eth_daddr) %>
				<% host_index = hosts.index(@packet.eth_daddr) %>
				<% usage[host_index] = usage[host_index].to_i + @packet.size.to_i %>
			<% else %>
				<% hosts.push(@packet.eth_daddr) %>
				<% sum = @packet.size.to_i %>
				<% usage.push(sum) %>
			<% end %>
		<% end %>
	<% else %>
		<% unknwn = unknwn + 1 %>
		<% sniff = @packet.peek %>
		<% packet_src = [sniff[20..21], sniff[22..23], sniff[24..25], sniff[26..27], sniff[28..29], sniff[30..31]] %>
		<% packet_dst = [sniff[8..9], sniff[10..11], sniff[12..13], sniff[14..15], sniff[16..17], sniff[18..19]] %>

		<% if types.include?(sniff[0])%>
			<% type_index = types.index(sniff[0]) %>
			<% counts[type_index] = counts[type_index] + 1 %>
		<% else %>
			<% types.push(sniff[0]) %>
			<% counts.push(1) %>
		<% end %>

		<% if hosts.include?(packet_dst.join(":")) %>
			<% host_index = hosts.index(packet_dst.join(":")) %>
			<% usage[host_index] = usage[host_index].to_i + @packet.size.to_i %>
		<% else %>
			<% hosts.push(packet_dst.join(":")) %>
			<% sum = @packet.size.to_i %>
			<% usage.push(sum) %>
		<% end %>
	<% end %>
<% end %>

<% hosts_s = Array.new %>
<% usage_s = Array.new %>

<% @packet_array.each do |pkt| %>
	<% @packet = PacketFu::Packet.parse(pkt) %>
	<% if(@packet.class != InvalidPacket) %>
		<% if @packet.is_ip? %>
			<% if hosts_s.include?(@packet.eth_saddr) %>
				<% host_index = hosts_s.index(@packet.eth_saddr) %>
				<% usage_s[host_index] = usage_s[host_index].to_i + @packet.size.to_i %>
			<% else %>
				<% hosts_s.push(@packet.eth_saddr) %>
				<% host_index = hosts_s.index(@packet.eth_saddr) %>
				<% sum = @packet.size.to_i %>
				<% usage_s.push(sum) %>
			<% end %>
		<% else %>
			<% if hosts_s.include?(@packet.eth_saddr) %>
				<% host_index = hosts_s.index(@packet.eth_saddr) %>
				<% usage_s[host_index] = usage_s[host_index].to_i + @packet.size.to_i %>
			<% else %>
				<% hosts_s.push(@packet.eth_saddr) %>
				<% host_index = hosts_s.index(@packet.eth_saddr) %>
				<% sum = @packet.size.to_i %>
				<% usage_s.push(sum) %>
			<% end %>
		<% end %>
	<% else %>
		<% sniff = @packet.peek %>
		<% packet_src = [sniff[20..21], sniff[22..23], sniff[24..25], sniff[26..27], sniff[28..29], sniff[30..31]] %>
		<% packet_dst = [sniff[8..9], sniff[10..11], sniff[12..13], sniff[14..15], sniff[16..17], sniff[18..19]] %>

		<% if hosts_s.include?(packet_src.join(":")) %>
			<% host_index = hosts_s.index(packet_src.join(":")) %>
			<% usage_s[host_index] = usage_s[host_index].to_i + @packet.size.to_i %>
		<% else %>
			<% hosts_s.push(packet_src.join(":")) %>
			<% host_index = hosts_s.index(packet_src.join(":")) %>
			<% sum = @packet.size.to_i %>
			<% usage_s.push(sum) %>
		<% end %>
	<% end %>
<% end %>

<% require 'mac_vendor' %>

<%# hosts.each do |e| %>
	<%# name = %x[curl https://mac-to-vendor.herokuapp.com/#{e}] %>
	<%# if name.to_s != "unkown" %>
		<%# host_index = hosts.index(e) %>
		<%# hosts[host_index.to_i] = name %>
	<%# end %>
<%# end %>

<%# chill = 1 %>
<%# hosts_s.each do |e| %>
	<%# name = %x[curl https://mac-to-vendor.herokuapp.com/#{e}] %>
	<%# if name != "unknown" %>
		<%#= chill %> <%#chill = chill + 1%>
		<%# host_index = hosts_s.index(e) %>
		<%# hosts_s[host_index] = name %>
	<%# end %>
<%# end %>

<center>
<div id="texts">
<h1 align="center"><%= "Usage of devices in #{@filename}" %></h1>
</div>

<div id="rcorners2">
<% @list = hosts.zip(usage) %>
<div id="boxes"><%= "Recieved"%></div>
<%= bar_chart @list, colors: ["#32cd32"] %>
</div>
<br>
<br>
<div id="rcorners2">
<div id="boxes"><%= "Sent"%></div>
<% @list2 = hosts_s.zip(usage_s) %>
<%= bar_chart @list2, colors: ["#32cd32"] %>
</div>
<br>
<br>

<div id="boxes"><%= "Protocol"%></div>
<% @list3 = types.zip(counts) %>
<%= pie_chart @list3 %>
<div id="boxes"><%= "Total packets: #{total}"%></div>
</div>

<div id="texts">
<h1> Upload another capture </h1>
</div>
<div id="texts" align="center">
<%= form_tag({action: :upload}, multipart: true) do %>
	<%= file_field_tag 'filename' %>
	<%= submit_tag("Upload") %>
	<% end %>
</div>

</center>

EPSI/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPSI</title>
    <%= csrf_meta_tags %>
    <% require 'packetfu' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>